# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem "curses", "~> 1.4"
gem 'console'

gem "rubocop", "~> 1.52"

gem "solargraph", "~> 0.49.0"

gem "sequel", "~> 5.69"

gem "mysql2", "~> 0.5.5"

gem "yaml", "~> 0.2.1"

gem "gtk3", "~> 4.1"

gem "reek", "~> 6.1"
